### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by nichujie** [nichujie/BartenderCheatSheet#6]
- [ ] Button/link to go back
- [ ] Align search results to center
- [ ] Loading style for search results

**Comment by FelixSelling** [comment]
All 3 features implemented:
https://github.com/nichujie/BartenderCheatSheet/tree/fs-branch-searchview

Only a simple "loading..." text atm, we can make a component usable for RandomDrink, Search and Detail

**Comment by FelixSelling** [comment]
Merged to main.
